
import { AlertCircle } from "lucide-react";

export function AdditionalInfo() {
  return (
    <section className="bg-white rounded-lg shadow-sm p-6 mb-8">
      <h2 className="text-2xl font-bold text-dark mb-6">
        Additional Information
      </h2>

      <div className="border-l-4 border-4 border-primary bg-primary-light/10 p-6 mb-6">
        <h3 className="text-xl font-semibold mb-2 text-dark">
          When to Seek Medical Help
        </h3>
        <p className="text-gray">
          This AI system provides general recommendations and is not a substitute for professional medical advice. Seek medical attention if you experience:
        </p>
        <ul className="list-disc pl-5 mt-2 text-gray">
          <li>Severe or worsening symptoms</li>
          <li>Allergic reactions (swelling, breathing issues, rash)</li>
          <li>High fever or persistent pain</li>
          <li>Chest pain, difficulty breathing, confusion, or fainting</li>
          <li>Severe medication side effects</li>
        </ul>
        <p className="text-gray mt-2 font-semibold">
          🚨 In emergencies, call 911 or visit the nearest hospital immediately.
        </p>
      </div>

      <div className="border-l-4 border-primary bg-primary-light/10 p-6 mb-6">
        <h3 className="text-xl font-semibold mb-2 text-dark">
          Lifestyle Recommendations
        </h3>
        <p className="text-gray">
          Rest as much as possible. Stay hydrated by drinking plenty of fluids, especially water, 
          clear broths, and warm teas with honey. Use a humidifier or take a steamy shower to help 
          ease congestion and coughing.
        </p>
      </div>

      <div className="border-l-4 border-destructive bg-destructive/5 p-6">
        <h3 className="text-xl font-semibold mb-2 text-destructive">
          Important Disclaimer
        </h3>
        <p className="text-gray">
          These recommendations are generated by an AI system based on the symptoms you provided and 
          should not be considered medical advice. Always consult with a healthcare professional before 
          starting any new medication or treatment regimen. If you have allergies, existing medical conditions, 
          or are taking other medications, consult your doctor or pharmacist before using any of these products.
        </p>
      </div>
    </section>
  );
}
